/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface AlertConfigurationDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  description?: string | null;
  isGlobal?: boolean;
  isActive?: boolean;
  /** @nullable */
  scheduledDate?: string | null;
  createdDate?: string;
  /** @nullable */
  idArea?: number | null;
  /** @nullable */
  areaName?: string | null;
  /** @nullable */
  idAgency?: number | null;
  /** @nullable */
  agencyName?: string | null;
}
