/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { AlertHistoryDto } from './alertHistoryDto';

export interface AlertHistoryDtoResponseDto {
  data?: AlertHistoryDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
