/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { AlertTypeDto } from './alertTypeDto';

export interface AlertTypeDtoResponseDto {
  data?: AlertTypeDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
