/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { AlertConfigurationDto } from './alertConfigurationDto';

export interface AlertConfigurationDtoResponseDto {
  data?: AlertConfigurationDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
