/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface AlertHistoryDto {
  id?: number;
  executionDate?: string;
  idAlertConfiguration?: number;
  /** @nullable */
  alertTitle?: string | null;
  /** @nullable */
  alertSubject?: string | null;
  idUser?: number;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  userEmail?: string | null;
}
