/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { AreaDto } from './areaDto';

export interface AreaDtoResponseDto {
  data?: AreaDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
