/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface AreaDto {
  id?: number;
  /** @nullable */
  nameArea?: string | null;
  isActive?: boolean;
  idAgency?: number;
  /** @nullable */
  agencyName?: string | null;
}
