/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface BooleanResponseDto {
  data?: boolean;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
