/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface DeviceDto {
  id?: number;
  quantity?: number;
  /** @nullable */
  brandName?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  observation?: string | null;
  isActive?: boolean;
  idDeviceType?: number;
  /** @nullable */
  deviceTypeName?: string | null;
  idUser?: number;
  /** @nullable */
  userName?: string | null;
  idArea?: number;
  /** @nullable */
  areaName?: string | null;
  /** @nullable */
  readonly fullDescription?: string | null;
}
