/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { DeviceDto } from './deviceDto';

export interface DeviceDtoResponseDto {
  data?: DeviceDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
