/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiAlertConfigurationsParams = {
SearchTerm?: string;
IsActive?: boolean;
IsGlobal?: boolean;
PageNumber?: number;
PageSize?: number;
};
