/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiNotificationsParams = {
IdUser?: number;
IdAlertType?: number;
IsRead?: boolean;
Keyword?: string;
PageNumber?: number;
PageSize?: number;
};
