/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiAreasParams = {
SearchName?: string;
SearchAgencyName?: string;
PageNumber?: number;
PageSize?: number;
};
