/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiUsersParams = {
IdRol?: number;
IdAgency?: number;
IdArea?: number;
Keyword?: string;
PageNumber?: number;
PageSize?: number;
};
