/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiMaintenanceHistoriesParams = {
IdMaintenance?: number;
IdDevice?: number;
IdUser?: number;
IdTypeDevice?: number;
PageNumber?: number;
PageSize?: number;
};
