/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiDevicesParams = {
IdUser?: number;
IdArea?: number;
IdDeviceType?: number;
SearchTerm?: string;
PageNumber?: number;
PageSize?: number;
};
