/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export type GetApiImpactsParams = {
Name?: string;
PageNumber?: number;
PageSize?: number;
};
