/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceAreaChartDto } from './maintenanceAreaChartDto';
import type { MaintenanceFrequencyChartDto } from './maintenanceFrequencyChartDto';
import type { MaintenanceMonthlyHistoryDto } from './maintenanceMonthlyHistoryDto';
import type { MaintenanceStatusDto } from './maintenanceStatusDto';

export interface MaintenanceDashboardDataDto {
  totalProgramados?: number;
  totalRealizados?: number;
  totalVencidos?: number;
  tiempoTotalEjecucion?: number;
  /** @nullable */
  porEstado?: MaintenanceStatusDto[] | null;
  /** @nullable */
  porFrecuencia?: MaintenanceFrequencyChartDto[] | null;
  /** @nullable */
  porArea?: MaintenanceAreaChartDto[] | null;
  /** @nullable */
  historialMensual?: MaintenanceMonthlyHistoryDto[] | null;
}
