/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceCalendarDto } from './maintenanceCalendarDto';

export interface MaintenanceCalendarDtoListResponseDto {
  /** @nullable */
  data?: MaintenanceCalendarDto[] | null;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
