/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceDto {
  id?: number;
  /** @nullable */
  details?: string | null;
  notificationDate?: string;
  completionDate?: string;
  executionTime?: number;
  createdDate?: string;
  idMaintenanceType?: number;
  /** @nullable */
  maintenanceTypeName?: string | null;
  idArea?: number;
  /** @nullable */
  areaName?: string | null;
  idDevice?: number;
  /** @nullable */
  deviceCode?: string | null;
  /** @nullable */
  deviceBrand?: string | null;
  /** @nullable */
  readonly deviceFullDescription?: string | null;
}
