/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceFrequencyDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  daysInterval?: number;
  createdDate?: string;
}
