/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceStatusDto {
  /** @nullable */
  estado?: string | null;
  cantidad?: number;
  /** @nullable */
  color?: string | null;
}
