/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceAreaChartDto {
  /** @nullable */
  area?: string | null;
  cantidad?: number;
}
