/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceHistoryDto {
  id?: number;
  solutionTime?: number;
  createdDate?: string;
  idMaintenance?: number;
  /** @nullable */
  maintenanceDetails?: string | null;
  idDevice?: number;
  /** @nullable */
  deviceCode?: string | null;
  /** @nullable */
  deviceBrand?: string | null;
  /** @nullable */
  deviceType?: string | null;
  idUser?: number;
  /** @nullable */
  technicalName?: string | null;
  /** @nullable */
  technicalEmail?: string | null;
}
