/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceFrequencyDto } from './maintenanceFrequencyDto';

export interface MaintenanceFrequencyDtoResponseDto {
  data?: MaintenanceFrequencyDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
