/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceDashboardDataDto } from './maintenanceDashboardDataDto';

export interface MaintenanceDashboardDataDtoResponseDto {
  data?: MaintenanceDashboardDataDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
