/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceDto } from './maintenanceDto';

export interface MaintenanceDtoResponseDto {
  data?: MaintenanceDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
