/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface MaintenanceCalendarDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  start?: string;
  end?: string;
  /** @nullable */
  details?: string | null;
  /** @nullable */
  deviceName?: string | null;
  /** @nullable */
  frequencyName?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  color?: string | null;
}
