/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { MaintenanceHistoryDto } from './maintenanceHistoryDto';

export interface MaintenanceHistoryDtoResponseDto {
  data?: MaintenanceHistoryDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
