/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface NotificationDto {
  id?: number;
  /** @nullable */
  textMessage?: string | null;
  /** @nullable */
  sentAt?: string | null;
  isRead?: boolean;
  idReference?: number;
  createdDate?: string;
  idUser?: number;
  /** @nullable */
  userEmail?: string | null;
  /** @nullable */
  userName?: string | null;
  idAlertType?: number;
  /** @nullable */
  alertTypeName?: string | null;
}
