/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { NotificationHistoryDto } from './notificationHistoryDto';

export interface NotificationHistoryDtoResponseDto {
  data?: NotificationHistoryDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
