/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface NotificationHistoryDto {
  id?: number;
  idUser?: number;
  idNotification?: number;
  actionDate?: string;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  userEmail?: string | null;
  idReference?: number;
  isRead?: boolean;
  /** @nullable */
  textMessage?: string | null;
}
