/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { NotificationDto } from './notificationDto';

export interface NotificationDtoResponseDto {
  data?: NotificationDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
