/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface OrganizationDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  logo?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  address?: string | null;
}
