/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { PriorityDto } from './priorityDto';

export interface PriorityDtoResponseDto {
  data?: PriorityDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
