/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface RenewMaintenanceDto {
  notificationDate: string;
  completionDate: string;
  /** @minLength 1 */
  details: string;
  executionTime: number;
  idMaintenanceFrequency?: number;
}
