/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface ResetPasswordDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  newPassword?: string | null;
}
