/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { ResolutionDto } from './resolutionDto';

export interface ResolutionDtoResponseDto {
  data?: ResolutionDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
