/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface ResolutionDto {
  id?: number;
  idTicket?: number;
  /** @nullable */
  actionTaken?: string | null;
  resolutionDate?: string;
  /** @nullable */
  rootCause?: string | null;
  /** @nullable */
  preventiveMeasures?: string | null;
  /** @nullable */
  observation?: string | null;
  /** @nullable */
  secondObservation?: string | null;
  solutionTime?: number;
  createdDate?: string;
  idUser?: number;
  /** @nullable */
  userName?: string | null;
  idSolutionStatus?: number;
  /** @nullable */
  solutionStatusName?: string | null;
  /** @nullable */
  idDevice?: number | null;
  /** @nullable */
  deviceName?: string | null;
  idPriority?: number;
  /** @nullable */
  priorityName?: string | null;
  /** @nullable */
  ticketDescription?: string | null;
  /** @nullable */
  ticketCreatorName?: string | null;
  /** @nullable */
  ticketAreaName?: string | null;
}
