/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { SoftwareSystemDto } from './softwareSystemDto';

export interface SoftwareSystemDtoResponseDto {
  data?: SoftwareSystemDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
