/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { SolutionStateDto } from './solutionStateDto';

export interface SolutionStateDtoIEnumerableResponseDto {
  /** @nullable */
  data?: SolutionStateDto[] | null;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
