/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface TicketDto {
  id?: number;
  reportDate?: string;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  idUser?: number;
  /** @nullable */
  userName?: string | null;
  idTypeError?: number;
  /** @nullable */
  typeErrorName?: string | null;
  idArea?: number;
  /** @nullable */
  areaName?: string | null;
  idSoftwareSystem?: number;
  /** @nullable */
  softwareSystemName?: string | null;
  idImpact?: number;
  /** @nullable */
  impactName?: string | null;
  idPriority?: number;
  /** @nullable */
  priorityName?: string | null;
  idSolutionState?: number;
  /** @nullable */
  solutionStatusName?: string | null;
  /** @nullable */
  idUserAssigned?: number | null;
  /** @nullable */
  assignedUserName?: string | null;
}
