/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TicketHistoryDto } from './ticketHistoryDto';

export interface TicketHistoryDtoResponseDto {
  data?: TicketHistoryDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
