/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface TicketHistoryDto {
  id?: number;
  closeDate?: string;
  createdDate?: string;
  idTicket?: number;
  /** @nullable */
  ticketDescription?: string | null;
  /** @nullable */
  softwareSystemName?: string | null;
  idResolution?: number;
  /** @nullable */
  actionTaken?: string | null;
  /** @nullable */
  rootCause?: string | null;
  solutionTime?: number;
  idUser?: number;
  /** @nullable */
  userName?: string | null;
}
