/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TicketDto } from './ticketDto';

export interface TicketDtoResponseDto {
  data?: TicketDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
