/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TypeMaintenanceDto } from './typeMaintenanceDto';

export interface TypeMaintenanceDtoIEnumerableResponseDto {
  /** @nullable */
  data?: TypeMaintenanceDto[] | null;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
