/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TypeDevicesDto } from './typeDevicesDto';

export interface TypeDevicesDtoResponseDto {
  data?: TypeDevicesDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
