/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TypeMaintenanceDto } from './typeMaintenanceDto';

export interface TypeMaintenanceDtoPagedResponseDto {
  status?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: TypeMaintenanceDto[] | null;
  currentPage?: number;
  totalPages?: number;
  pageSize?: number;
  totalItems?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  totalActivos?: number;
  totalInactivos?: number;
  activeTicketsCount?: number;
  resolvedTodayCount?: number;
}
