/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface TypeErrorDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  createdDate?: string;
}
