/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */
import type { TypeErrorDto } from './typeErrorDto';

export interface TypeErrorDtoResponseDto {
  data?: TypeErrorDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
