/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UpdateMaintenanceFrequecyDto {
  /**
     * @minLength 1
     * @maxLength 60
     */
  name: string;
  daysInterval: number;
}
