/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UpdateAlertTypeDto {
  /**
     * @minLength 0
     * @maxLength 60
     */
  name: string;
}
