/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UpdateMaintenanceDto {
  idMaintenanceType: number;
  idArea: number;
  idDevice: number;
  notificationDate: string;
  completionDate?: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  details: string;
  executionTime?: number;
}
