/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UpdateAreaDto {
  /**
     * @minLength 0
     * @maxLength 60
     */
  nameArea: string;
  isActive?: boolean;
  idAgency?: number;
}
