/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UserRegisterDto {
  /**
     * @minLength 0
     * @maxLength 60
     */
  firstName: string;
  /**
     * @minLength 0
     * @maxLength 60
     */
  lastName: string;
  /**
     * @minLength 4
     * @maxLength 50
     * @pattern ^[a-zA-Z0-9_\.]+$
     */
  userName: string;
  /**
     * @minLength 0
     * @maxLength 240
     */
  email: string;
  /**
     * @minLength 8
     * @maxLength 100
     */
  password: string;
  /**
     * @minLength 0
     * @maxLength 13
     * @nullable
     */
  phoneNumber?: string | null;
  /** @minimum 1 */
  idRol: number;
  /** @minimum 1 */
  idAgency: number;
  /** @minimum 1 */
  idArea: number;
}
