/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * HelpDesk API
 * OpenAPI spec version: v1
 */

export interface UserLoginDto {
  /** @nullable */
  email: string | null;
  /** @nullable */
  password: string | null;
}
